export const seedItems = [
  { path: 'C:\\', name: 'C:\\', type: 'folder', parentPath: null, content: null },
  { path: 'C:\\Users', name: 'Users', type: 'folder', parentPath: 'C:\\', content: null },
  { path: 'C:\\Users\\Desktop', name: 'Desktop', type: 'folder', parentPath: 'C:\\Users', content: null },
  { path: 'C:\\Users\\Documents', name: 'Documents', type: 'folder', parentPath: 'C:\\Users', content: null },
  { path: 'C:\\Users\\Downloads', name: 'Downloads', type: 'folder', parentPath: 'C:\\Users', content: null },
  { path: 'C:\\Users\\Desktop\\Screenshots', name: 'Screenshots', type: 'folder', parentPath: 'C:\\Users\\Desktop', content: null },
  { path: 'C:\\Users\\Documents\\Architecture', name: 'Architecture', type: 'folder', parentPath: 'C:\\Users\\Documents', content: null },
  { path: 'C:\\Users\\Documents\\Scripts', name: 'Scripts', type: 'folder', parentPath: 'C:\\Users\\Documents', content: null },
  { path: 'C:\\Program Files', name: 'Program Files', type: 'folder', parentPath: 'C:\\', content: null },
  { path: 'C:\\Windows', name: 'Windows', type: 'folder', parentPath: 'C:\\', content: null },
  { path: 'C:\\Windows\\System32', name: 'System32', type: 'folder', parentPath: 'C:\\Windows', content: null },
  {
    path: 'C:\\Users\\Desktop\\Project Brief.txt',
    name: 'Project Brief.txt',
    type: 'file',
    parentPath: 'C:\\Users\\Desktop',
    content: 'Finalize file explorer integration and persistence layer.',
  },
  {
    path: 'C:\\Users\\Desktop\\Screenshots\\desktop-home.png',
    name: 'desktop-home.png',
    type: 'file',
    parentPath: 'C:\\Users\\Desktop\\Screenshots',
    content: '',
  },
  {
    path: 'C:\\Users\\Documents\\System Notes.md',
    name: 'System Notes.md',
    type: 'file',
    parentPath: 'C:\\Users\\Documents',
    content: 'Current app is frontend-only. Backend integration still pending.',
  },
  {
    path: 'C:\\Users\\Documents\\Architecture\\backend-plan.txt',
    name: 'backend-plan.txt',
    type: 'file',
    parentPath: 'C:\\Users\\Documents\\Architecture',
    content: 'SQLite schema: id, name, type, parent_id, content, created_at, updated_at.',
  },
  {
    path: 'C:\\Users\\Documents\\Scripts\\backup.bat',
    name: 'backup.bat',
    type: 'file',
    parentPath: 'C:\\Users\\Documents\\Scripts',
    content: 'rem Back up project notes\nmkdir C:\\Users\\Documents\\Backup\ncopy C:\\Users\\Desktop\\Project Brief.txt C:\\Users\\Documents\\Backup\necho Backup completed at %DATE% %TIME%',
  },
  {
    path: 'C:\\Users\\Documents\\Scripts\\launch-apps.bat',
    name: 'launch-apps.bat',
    type: 'file',
    parentPath: 'C:\\Users\\Documents\\Scripts',
    content: 'rem Launch simulated applications\nstart notepad\nstart file-explorer\nstart task-manager\ntasklist',
  },
  {
    path: 'C:\\Users\\Documents\\Scripts\\network-check.bat',
    name: 'network-check.bat',
    type: 'file',
    parentPath: 'C:\\Users\\Documents\\Scripts',
    content: 'rem Network diagnostic automation\nipconfig\nping gateway.local\nnetstat\nconnect fileserver.local 445',
  },
  {
    path: 'C:\\Users\\Documents\\Scripts\\setup-workspace.bat',
    name: 'setup-workspace.bat',
    type: 'file',
    parentPath: 'C:\\Users\\Documents\\Scripts',
    content: 'rem Create folders and reusable files\nset PROJECT=OSDemo\nmkdir C:\\Users\\Desktop\\%PROJECT%\nwrite C:\\Users\\Desktop\\%PROJECT%\\readme.txt Project workspace created\nif exist C:\\Users\\Desktop\\%PROJECT%\\readme.txt echo Workspace ready',
  },
  {
    path: 'C:\\Users\\Downloads\\installer.exe',
    name: 'installer.exe',
    type: 'file',
    parentPath: 'C:\\Users\\Downloads',
    content: '',
  },
  {
    path: 'C:\\Users\\Downloads\\report.pdf',
    name: 'report.pdf',
    type: 'file',
    parentPath: 'C:\\Users\\Downloads',
    content: '',
  },
];
