export const seedItems = [
  { path: 'C:\\', name: 'C:\\', type: 'folder', parentPath: null, content: null },
  { path: 'C:\\Users', name: 'Users', type: 'folder', parentPath: 'C:\\', content: null },
  { path: 'C:\\Users\\Desktop', name: 'Desktop', type: 'folder', parentPath: 'C:\\Users', content: null },
  { path: 'C:\\Users\\Documents', name: 'Documents', type: 'folder', parentPath: 'C:\\Users', content: null },
  { path: 'C:\\Users\\Downloads', name: 'Downloads', type: 'folder', parentPath: 'C:\\Users', content: null },
  { path: 'C:\\Users\\Desktop\\Screenshots', name: 'Screenshots', type: 'folder', parentPath: 'C:\\Users\\Desktop', content: null },
  { path: 'C:\\Users\\Documents\\Architecture', name: 'Architecture', type: 'folder', parentPath: 'C:\\Users\\Documents', content: null },
  { path: 'C:\\Program Files', name: 'Program Files', type: 'folder', parentPath: 'C:\\', content: null },
  { path: 'C:\\Windows', name: 'Windows', type: 'folder', parentPath: 'C:\\', content: null },
  { path: 'C:\\Windows\\System32', name: 'System32', type: 'folder', parentPath: 'C:\\Windows', content: null },
  {
    path: 'C:\\Users\\Desktop\\Project Brief.txt',
    name: 'Project Brief.txt',
    type: 'file',
    parentPath: 'C:\\Users\\Desktop',
    content: 'Finalize file explorer integration and persistence layer.',
  },
  {
    path: 'C:\\Users\\Desktop\\Screenshots\\desktop-home.png',
    name: 'desktop-home.png',
    type: 'file',
    parentPath: 'C:\\Users\\Desktop\\Screenshots',
    content: '',
  },
  {
    path: 'C:\\Users\\Documents\\System Notes.md',
    name: 'System Notes.md',
    type: 'file',
    parentPath: 'C:\\Users\\Documents',
    content: 'Current app is frontend-only. Backend integration still pending.',
  },
  {
    path: 'C:\\Users\\Documents\\Architecture\\backend-plan.txt',
    name: 'backend-plan.txt',
    type: 'file',
    parentPath: 'C:\\Users\\Documents\\Architecture',
    content: 'SQLite schema: id, name, type, parent_id, content, created_at, updated_at.',
  },
  {
    path: 'C:\\Users\\Downloads\\installer.exe',
    name: 'installer.exe',
    type: 'file',
    parentPath: 'C:\\Users\\Downloads',
    content: '',
  },
  {
    path: 'C:\\Users\\Downloads\\report.pdf',
    name: 'report.pdf',
    type: 'file',
    parentPath: 'C:\\Users\\Downloads',
    content: '',
  },
];
